name: 'stably-runner'
description: 'Use this Github action to run tests on https://stably.ai/'
author: 'Stably'

# Define your inputs here.
inputs:
  api-key:
    description: 'Your API key'
    required: true
  run-group-ids:
    description: |-
      Newline separated list of run group IDs.
      Use to run a subset of tests.
    deprecationMessage:
      'Only a single run-group-id is supported. Prefer the use test-group-id
      instead.'
  test-group-id:
    description: The test group ID to execute
    required: true
  domain-override:
    description: |-
      Newline-separated tuple (pair) with original first as first line and the replacement second.
      Use to replace website URLs when running tests
    deprecationMessage:
      'This input is deprecated. Please use the url-replacement input instead.'
  replacement-url:
    description: |-
      Newline-separated tuple (pair) with original first as first line and the replacement second.
      Use to replace website URLs when running tests
  github-comment:
    description: |-
      If enabled, will leave a comment on either the commit or PR with relevant test results.
      Requires proper permissions.
    default: 'true'
  github-token:
    description: |-
      This token is used for used for leaving the comments on PRs/commits.
      By default, we'll use the github actions bot token, but you can override this a repo scoped PAT.
    default: ${{ github.token }}
  async:
    description: |-
      If set, will launch the tests but not wait for them to finish and the action will always output success.
      Note: Github comments will not function if this is set
    default: 'false'

# Define your outputs here.
outputs:
  success:
    description: 'Bool if run was successful'

runs:
  using: node20
  main: dist/index.js

branding:
  icon: 'cloud-lightning'
  color: 'orange'
