name: 'stably-runner'
description: 'Use this Github action to run tests on https://stably.ai/'
author: 'Stably'

# Define your inputs here.
inputs:
  api-key:
    description: 'Your API key'
    required: true
  project-id:
    description: |-
      The project ID to execute (v2 only).
      Use this OR test-suite-id, not both.
  run-group-name:
    description: |-
      The Playwright project name to run (v2 only).
      Optional - if not provided, all projects will run.
  env-overrides:
    description: |-
      A YAML string or JSON object containing environment variable overrides (v2 only).
      Each key is a variable name and the value is a string.
      Example:
        BASE_URL: https://staging.example.com
        API_KEY: abc123
  test-group-id:
    description: The test group ID to execute (v1 only)
    deprecationMessage:
      'We renamed test groups to test suites. Use test-suite-id instead.'
  test-suite-id:
    description: |-
      The test suite ID to execute (v1 only).
      Use this OR project-id, not both.
  domain-override:
    description: |-
      Newline-separated tuple (pair) with original first as first line and the replacement second (v1 only).
      Use to replace website URLs when running tests
    deprecationMessage:
      'This input is deprecated. Please use the url-replacement input instead.'
  url-replacement:
    description: |-
      Newline-separated tuple (pair) with original first as first line and the replacement second (v1 only).
      Use to replace website URLs when running tests
    deprecationMessage:
      'URL replacement is deprecated. Please use environment variables instead.'
  github-comment:
    description: |-
      If enabled, will leave a comment on either the commit or PR with relevant test results.
      Requires proper permissions.
    default: 'true'
  github-token:
    description: |-
      This token is used for used for leaving the comments on PRs/commits.
      By default, we'll use the github actions bot token, but you can override this a repo scoped PAT.
    default: ${{ github.token }}
  async:
    description: |-
      If set, will launch the tests but not wait for them to finish and the action will always output success.
      Note: Github comments will not function if this is set
    default: 'false'
  environment:
    description: |-
      The environment to inherit variables from (v1 only, v2 support soon).
      Defaults to 'PRODUCTION'.
    default: 'PRODUCTION'
  variable-overrides:
    description: |-
      A JSON object of variable overrides to pass to the tests (v1 only).
      The key is the variable name and the value is the value to override it with.
      The value can be a string or an object with a 'value' property and an optional 'sensitive' property.
    default: '{}'
  note:
    description: |-
      Optional note to add to the test run to help identify it (v1 only).
      This note will be included in the test run metadata.

# Define your outputs here.
outputs:
  success:
    description: 'Bool if run was successful'
  testSuiteRunId:
    description: 'The resulting test-suite-run-id (v1 only)'
  runId:
    description: 'The resulting run-id (v2 only)'

runs:
  using: node24
  main: dist/index.js

branding:
  icon: 'cloud-lightning'
  color: 'orange'
