name: 'stably-runner'
description: 'Use this Github action to run tests on https://stably.ai/'
author: 'Stably'

# Define your inputs here.
inputs:
  project-id:
    description: 'Your project ID'
    required: true
  api-key:
    description: 'Your API key'
    required: true
  test-ids:
    description: |-
      Newline separated list of test IDs.
      Use to run a subset of tests
  run-group-ids:
    description: |-
      Newline separated list of run group IDs.
      Use to run a subset of tests.
  domain-overrides:
    description: |-
      Newline-separated list of domain overrides (given in pairs -- original first, replacement second).
      Use to replace origin URLs when running tests

# Define your outputs here.
outputs:
  success:
    description: 'Bool if run was successful'

runs:
  using: node20
  main: dist/index.js

branding:
  icon: 'cloud-lightning'
  color: 'orange'
