name: Pull Request

on:
  pull_request:

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Start nginx
        run: docker compose -f test/docker-compose.yaml up -d

      - name: Test changes
        uses: ./
        with:
          api-key: ${{ secrets.API_KEY }}
          test-group-id: cm51jnwks0001l103b5lrprjs
          url-replacement: |-
            https://nginx.com
            http://localhost:8080
